http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: false

input:
  csv:
    paths: [${FILESIREN}/cj_sept2022.csv]
    parse_header_row: true
    delimiter: ';'

pipeline:
  threads: 8
  processors:
    - mapping: |
        root.codecj = this.codecj
        root.designationcj = this.designationcj
   
output:
  broker:
    batching:
      count: 4500
      period: 25s
    outputs:
      - retry:
          max_retries: 5
          backoff:
            initial_interval: 1s
            max_interval: 30s
          output:
            sql_insert:
              driver: postgres
              dsn: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${IPHOST}:5432/${POSTGRES_DB}?sslmode=disable
              table: categorie_juridique
              columns: [codecj,designationcj]
              args_mapping: root = [codecj,designationcj]
              init_statement: |
                  CREATE TABLE IF NOT EXISTS categorie_juridique (
                    codecj VARCHAR(4),
                    designationcj VARCHAR(150),
                    primary key (codecj)
                  );
                  CREATE INDEX IF NOT EXISTS codecj_idx ON categorie_juridique (codecj);

logger:
  level: DEBUG
