http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: false
  cert_file: ""
  key_file: ""
 
input:
  file:
    paths: ["${FILESIREN}/GeolocalisationEtablissement_Sirene_pour_etudes_statistiques_utf8.zip"]
    codec: all-bytes

pipeline:
  processors:
  - label: "unzip_the_file"
    unarchive:
      format: zip

output:
  file:
    path: "${FILESIREN}/GeolocalisationEtablissement_Sirene_pour_etudes_statistiques_utf8.csv" 
    codec: all-bytes

logger:
  level: INFO
  format: logfmt
  add_timestamp: false
  level_name: level
  timestamp_name: time
  message_name: msg
  static_fields:
    '@service': redpanda-connect


