http:
  enabled: true
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: false
  cert_file: ""
  key_file: ""
 
input:
  read_until:
    input:
      http_client:
        url: "https://www.data.gouv.fr/fr/datasets/r/825f4199-cadd-486c-ac46-a65a8ea1a047"
        verb: GET
        timeout: "1800s"
    check: true 
     
pipeline:
  threads: 4
  processors:
  - label: "unzip_the_downloaded_file"
    unarchive:
      format: zip

output:
  file:
    path: "/home/ubuntu/Files_Siren/StockUniteLegale_utf8.csv"
    codec: all-bytes



logger:
  level: INFO
  format: logfmt
  add_timestamp: false
  level_name: level
  timestamp_name: time
  message_name: msg
  static_fields:
    '@service': redpanda-connect

