global:
  scrape_interval: 25s
  evaluation_interval: 15s
  external_labels:
    monitor: "Siren-Project"

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "postgres_exporter"  # Utilisez un exporter dédié
    static_configs:
      - targets: ["postgres_exporter:9187"]  # Port par défaut de l'exporter PostgreSQL

  - job_name: "pushgateway"
    honor_labels: true # Critical for Pushgateway to avoid label conflicts
    static_configs:
      - targets: ["pushgateway:9091"] # Use the service name if in the same Docker network
        labels:
          service: "pushgateway"

