name: Test and Deploy Siren

on:
  push:
    branches:
      - dev

jobs:
  test-siren:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock psycopg2-binary python-dotenv prometheus-client bcrypt
          pip show python-dotenv
          
      - name: Run specific tests
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB_USER: ${{ secrets.POSTGRES_DB_USER }}
          IPHOST: ${{ secrets.IPHOST }}
        run: pytest siren/UserTable_Join/tests/{inner_join_test,user_table_test}.py

  deploy-to-prod:
    needs: test-siren
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
      
      - name: Prepare prod branch
        run: |
          git config --global user.email "lionel.matter@outlook.fr"
          git config --global user.name "MatterLMA"
          mkdir -p /tmp/siren
          cp -r siren/* /tmp/siren/
      
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: prod
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update siren in prod branch
        run: |
          rm -rf siren
          cp -r /tmp/siren/ .
      
      - name: Commit and push changes to prod
        run: |
          git config --global user.email "lionel.matter@outlook.fr"
          git config --global user.name "MatterLMA"
          git add siren/
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update siren folder from dev branch (GitHub Actions)"
            git push origin prod
          else
            echo "No changes to siren folder"

  deploy-to-main:
    needs: deploy-to-prod
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v4
        with:
          ref: prod
      
      - name: Push to main
        run: |
          git config --global user.email "lionel.matter@outlook.fr"
          git config --global user.name "MatterLMA"
          git push origin prod:main
