name: Test and Deploy Siren

on:
  push:
    branches:
      - dev

jobs:
  test-and-deploy-siren:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB_USER: ${{ secrets.POSTGRES_DB_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          IPHOST: ${{ secrets.IPHOST }}
        ports:
          - 5432:5432
        # Add healthcheck to ensure PostgreSQL is ready
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
         ref: dev
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest python-dotenv psycopg2 requests prometheus_client bcrypt
      
      - name: Run specific tests
        run: pytest test_UserTable_Join/{inner_join_test,user_table_test}.py
    
      - name: Prepare main branch
        if: success()
        run: |
          # Configure git
          git config --global user.email "lionel.matter@oultook.fr"
          
          # Create temporary directory
          mkdir -p /tmp/siren
          cp -r siren/* /tmp/siren/
    
      - name: Checkout main branch
        if: success()
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Update siren in main branch
        if: success()
        run: |
          # Remove existing siren folder and copy new version
          rm -rf siren
          cp -r /tmp/siren/ .
    
      - name: Commit and push changes
        if: success()
        run: |
          git add siren/
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update siren folder from dev branch (GitHub Actions)"
            git push origin main
          else
            echo "No changes to siren folder"
          fi
          
